// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://tccoywsgyarygqacaqih.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRjY295d3NneWFyeWdxYWNhcWloIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjE3MTk5NzcsImV4cCI6MjA3NzI5NTk3N30.tHxgpZ6x72B7wMlcNZV3tkdRhunJw8en9xO8pvnBmmo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});